# This file contains values from Cookiecutter

default_context:
  project_name: "driver-stalker"
  project_slug: "driver_stalker"
  project_description: "Awesome `driver-stalker` project!"
  username: "Awesome user"
  email: "awesome-user@example.com"
  vcs_remote_type: "github"
  minimal_python_version: "3.10"
  version: "0.1.0"
  line_length: "100"

  python_linter: "ruff"
  python_formatter: "ruff"

  include_mypy_type_checker: "y"
  include_cli_example: "n"
  include_docker_sample: "n"
  include_tests_sample: "n"
  include_notebooks_sample: "y"
